### ISSUE TITLE
notify: false not working

### ISSUE THREAD

**Issue by shaneparsons** [JeffreyWay/laravel-elixir-browsersync-official#2]
Not sure if this issue belongs here or further up, but setting `notify: false` in my gulpfile, or even in _laravel-elixir/dist/config.js_ doesn't stop the notifications.

I've had this working in the past with other projects.

```
"laravel-elixir": "^6.0.0-11",
"laravel-elixir-browsersync-official": "^1.0.0"
```

**Comment by JeffreyWay** [comment]
Please paste in the relevant portion of your Gulpfile.

**Comment by shaneparsons** [comment]
It turns out it was the `notifications: true` portion of the config.js that was showing notifications... not browsersync.

**Comment by giovannipds** [comment]
Seems like the 5.4 webpack mix is having the same issue... =S
